from abc import ABCMeta, abstractmethod
from typing import Tuple, Optional, Sequence
from torch import Tensor
import torch

from alphagen.data.expression import Expression


class AlphaCalculator(metaclass=ABCMeta):
    @abstractmethod
    def calc_single_IC_ret(self, expr: Expression) -> float:
        'Calculate IC between a single alpha and a predefined target.'


class TensorAlphaCalculator(AlphaCalculator):
    def __init__(self, target: Optional[Tensor]) -> None:
        self._target = target

    @property
    @abstractmethod
    def n_days(self) -> int: ...

    @property
    def target(self) -> Tensor:
        if self._target is None:
            raise ValueError("A target must be set before calculating non-mutual IC.")
        return self._target

    @abstractmethod
    def evaluate_alpha(self, expr: Expression) -> Tensor:
        'Evaluate an alpha into a `Tensor`'

    def _calc_IC(self, value1: Tensor, value2: Tensor) -> float:
        # value1 and value2 are 1D tensors of shape [N]
        # Drop NaNs or Infs that might have been generated by invalid formulas
        valid_mask = torch.isfinite(value1) & torch.isfinite(value2)
        v1_valid = value1[valid_mask]
        v2_valid = value2[valid_mask]

        if len(v1_valid) < 2:
            return 0.0  # Cannot calculate correlation with less than 2 points

        # Calculate 1D Pearson Correlation
        vx = v1_valid - v1_valid.mean()
        vy = v2_valid - v2_valid.mean()
        
        covariance = (vx * vy).sum()
        std_x = torch.sqrt((vx ** 2).sum())
        std_y = torch.sqrt((vy ** 2).sum())
        
        # Add epsilon to prevent divide-by-zero
        ic = covariance / (std_x * std_y + 1e-8)
        
        return ic.item()
    

    def calc_single_IC_ret(self, expr: Expression) -> float:
        return self._calc_IC(self.evaluate_alpha(expr), self.target)